#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'solve' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER k
#  3. STRING s
#

def solve(n, k, s):

    s= [int(x) for x in s]
    rolling_sum=sum(s[:k+1])
 
    num_pairs=0
    for i in range(k,n+k):
        if s[i-k]:
            num_pairs+=2*rolling_sum-1
            rolling_sum-=1
        if i+1<n:
            rolling_sum+=s[i+1]
    
    d=math.gcd(num_pairs, n**2)
    
    return f'{int(num_pairs/d)}/{int(n**2/d)}'
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        first_multiple_input = input().rstrip().split()

        n = int(first_multiple_input[0])

        k = int(first_multiple_input[1])

        s = input()

        result = solve(n, k, s)

        fptr.write(result + '\n')

    fptr.close()
